<script setup>
// Thin wrapper around @heroicons/vue's 24px outline set, mirroring the
// server-side blade-ui-kit/blade-heroicons `o-*` icons used throughout the
// existing Blade views (e.g. <x-heroicon-o-book-open />), so Vue templates
// can reference icons by the same short name.
import {
  AcademicCapIcon,
  ArrowLeftIcon,
  ArrowTopRightOnSquareIcon,
  Bars3Icon,
  BookOpenIcon,
  BuildingStorefrontIcon,
  CalendarDaysIcon,
  CalendarIcon,
  ChatBubbleLeftIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ClipboardDocumentIcon,
  ClipboardIcon,
  ClockIcon,
  CodeBracketIcon,
  Cog6ToothIcon,
  ComputerDesktopIcon,
  DevicePhoneMobileIcon,
  EllipsisHorizontalIcon,
  EnvelopeIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  EyeIcon,
  EyeSlashIcon,
  FaceSmileIcon,
  FunnelIcon,
  GlobeAltIcon,
  InboxIcon,
  InformationCircleIcon,
  LinkIcon,
  MapIcon,
  MapPinIcon,
  MegaphoneIcon,
  MoonIcon,
  NewspaperIcon,
  PaintBrushIcon,
  PaperAirplaneIcon,
  PauseIcon,
  PencilSquareIcon,
  PhoneIcon,
  PlayIcon,
  PlusIcon,
  PrinterIcon,
  PuzzlePieceIcon,
  QrCodeIcon,
  QuestionMarkCircleIcon,
  RssIcon,
  ShareIcon,
  SignalSlashIcon,
  SquaresPlusIcon,
  SunIcon,
  TableCellsIcon,
  TagIcon,
  TruckIcon,
  VideoCameraIcon,
  XCircleIcon,
  XMarkIcon,
} from '@heroicons/vue/24/outline'

const ICONS = {
  'academic-cap': AcademicCapIcon,
  'arrow-left': ArrowLeftIcon,
  'arrow-top-right-on-square': ArrowTopRightOnSquareIcon,
  'bars-3': Bars3Icon,
  'book-open': BookOpenIcon,
  'building-storefront': BuildingStorefrontIcon,
  calendar: CalendarIcon,
  'calendar-days': CalendarDaysIcon,
  'chat-bubble-left': ChatBubbleLeftIcon,
  check: CheckIcon,
  'check-circle': CheckCircleIcon,
  'chevron-down': ChevronDownIcon,
  'chevron-left': ChevronLeftIcon,
  'chevron-right': ChevronRightIcon,
  clipboard: ClipboardIcon,
  'clipboard-document': ClipboardDocumentIcon,
  clock: ClockIcon,
  'code-bracket': CodeBracketIcon,
  'cog-6-tooth': Cog6ToothIcon,
  'computer-desktop': ComputerDesktopIcon,
  'device-phone-mobile': DevicePhoneMobileIcon,
  'ellipsis-horizontal': EllipsisHorizontalIcon,
  envelope: EnvelopeIcon,
  'exclamation-circle': ExclamationCircleIcon,
  'exclamation-triangle': ExclamationTriangleIcon,
  eye: EyeIcon,
  'eye-slash': EyeSlashIcon,
  'face-smile': FaceSmileIcon,
  funnel: FunnelIcon,
  'globe-alt': GlobeAltIcon,
  inbox: InboxIcon,
  'information-circle': InformationCircleIcon,
  link: LinkIcon,
  map: MapIcon,
  'map-pin': MapPinIcon,
  megaphone: MegaphoneIcon,
  moon: MoonIcon,
  newspaper: NewspaperIcon,
  'paint-brush': PaintBrushIcon,
  'paper-airplane': PaperAirplaneIcon,
  pause: PauseIcon,
  'pencil-square': PencilSquareIcon,
  phone: PhoneIcon,
  play: PlayIcon,
  plus: PlusIcon,
  printer: PrinterIcon,
  'puzzle-piece': PuzzlePieceIcon,
  'qr-code': QrCodeIcon,
  'question-mark-circle': QuestionMarkCircleIcon,
  rss: RssIcon,
  share: ShareIcon,
  'signal-slash': SignalSlashIcon,
  'squares-plus': SquaresPlusIcon,
  sun: SunIcon,
  'table-cells': TableCellsIcon,
  tag: TagIcon,
  truck: TruckIcon,
  'video-camera': VideoCameraIcon,
  'x-circle': XCircleIcon,
  'x-mark': XMarkIcon,
}

defineProps({
  name: {
    type: String,
    required: true,
  },
})
</script>

<template>
  <component :is="ICONS[name]" aria-hidden="true" />
</template>
