<?php

use App\Models\LearningProgress;
use App\Models\StudentSchedule;
use App\ViewModels\LearningProgressViewModel;
use Illuminate\Support\Carbon;

// simple smoke test generated by artisan

test('viewmodel calculates completion percentage correctly', function () {
    // create a bare model instance; we just need uuid and name
    $schedule = new StudentSchedule;
    $schedule->uuid = \Ramsey\Uuid\Uuid::uuid4()->toString();
    $schedule->name = 'Demo';

    // sample courses and weeks
    $courses = [
        ['id' => 1, 'code' => 'A', 'name' => 'Course A'],
        ['id' => 2, 'code' => 'B', 'name' => 'Course B'],
    ];

    $weeks = [
        ['num' => 1, 'start' => '2026-01-01', 'end' => '2026-01-07'],
        ['num' => 2, 'start' => '2026-01-08', 'end' => '2026-01-14'],
    ];

    $progressData = [
        1 => [
            1 => ['video' => true, 'textbook' => true],
            2 => ['video' => false, 'textbook' => true],
        ],
        2 => [
            1 => ['video' => true, 'textbook' => true],
            2 => ['video' => true, 'textbook' => true],
        ],
    ];

    $learning = new LearningProgress;
    $learning->id = 999;
    $learning->term = '2025B';
    $learning->progress = $progressData;
    $learning->notes = [];

    $semesterStart = Carbon::parse('2026-01-01');
    $semesterEnd = Carbon::parse('2026-05-01');

    $vm = LearningProgressViewModel::fromModel(
        $learning,
        $schedule,
        $courses,
        $weeks,
        $semesterStart,
        $semesterEnd,
    );

    // two courses × two weeks × 2 items (video + textbook) = 8 total
    expect($vm->totalCount)->toEqual(8);
    // above progress data contains seven completed items
    expect($vm->completedCount)->toEqual(7);
    expect($vm->percentage)->toBe(87.5);
});
